---
title: "PopsAdrianna_GroupHistogram"
author: "Adrianna Pops"
date: "2024-09-29"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
#install.packages("colorspace")
library(colorspace)

#read the sample data into r
CrimeRate_df <- read_csv("/Users/ampops/Desktop/DSCI605LABS2/Sampledata2.csv")
#view(CrimeRate_df)

### use case_when to break CrimeRate into three groups: crimerate<250, 250<= crime rate <=500, crimerate >500 

cr_df2 <- CrimeRate_df %>% 
  select(CrimeRate, Year) %>% 
  mutate(RangeGroup = case_when(CrimeRate < 250 ~ "CrimeRate < 250", 
                          250 <= CrimeRate & CrimeRate <= 500 ~ "250 <= CrimeRate <= 500", 
                          CrimeRate > 500 ~ "CrimeRate > 500"))

### make two color vectors one using colorspace::diverge_hcl and one using c()
n1 <- length(unique(CrimeRate_df$Year))
col1=colorspace::diverge_hcl(n1)
col1

col2=c("green", "blue", "red")
col2

# plot a histogram CrimeRate filled with var Year using first color vector
CrimeRate_df %>% filter(Year %in% c(2007:2018)) %>% 
  ggplot(aes(x = CrimeRate, color = as.factor(Year), fill = as.factor(Year))) + 
  geom_histogram(position = "dodge", alpha = 0.5, bins = 10) +
  scale_color_manual(values = col1)+
  scale_fill_manual(values = col1)+
  labs(title = "Crime Rate Histogram Plots", x = "Crime rate per 1000 people", y = "count")+
  theme_classic()

# plot a histogram CrimeRate filled with var RangeGroup using seconc color vector
cr_df2 %>% filter(RangeGroup == "CrimeRate < 250" | RangeGroup == "250 <= CrimeRate <= 500"| RangeGroup == "CrimeRate > 500") %>% 
  ggplot(aes(x = CrimeRate, color = RangeGroup, fill  = RangeGroup)) +
  geom_histogram(position = "dodge", alpha = 0.5, bins = 10) +
  scale_color_manual(values = col2)+
  scale_fill_manual(values = col2)+
  labs(title = "Crime Rate Histogram Plots", x = "Crime rate per 1000 people", y = "count")
```
